.\"
.\" Author: Joao Marcelo Martins <marcelo.martins@rackspace.com> or <btorch@gmail.com>
.\" Copyright (c) 2010-2011 OpenStack, LLC.
.\"
.\" Licensed under the Apache License, Version 2.0 (the "License");
.\" you may not use this file except in compliance with the License.
.\" You may obtain a copy of the License at
.\"
.\"    http://www.apache.org/licenses/LICENSE-2.0
.\"
.\" Unless required by applicable law or agreed to in writing, software
.\" distributed under the License is distributed on an "AS IS" BASIS,
.\" WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
.\" implied.
.\" See the License for the specific language governing permissions and
.\" limitations under the License.
.\"  
.TH swift-init 1 "8/26/2011" "Linux" "OpenStack Swift"

.SH NAME 
.LP
.B swift-init
\- Openstack-swift swift-init tool

.SH SYNOPSIS
.LP
.B swift-init
 <server> [<server> ...] <command> [options]
 
.SH DESCRIPTION 
.PP
The swift-init tool can be used to initialize all swift daemons available as part of
openstack-swift. Instead of calling individual init.d scripts for each 
swift daemon, one can just use swift-init. With swift-init you can initialize 
just one swift service, such as the "proxy", or a combination of them. The tool also 
allows one to use the keywords such as "all", "main" and "rest" for the <server> argument.


.PP
\fBServers:\fR
.RS 2
\fIproxy\fR
.RS
Initializes the swift proxy daemon
.RE

\fIobject\fR, \fIobject-replicator\fR, 
\fIobject-auditor\fR, \fIobject-updater\fR
.RS
Initialize the swift object daemons above
.RE

\fIcontainer\fR, \fIcontainer-update\fR, 
\fIcontainer-replicator\fR, \fIcontainer-auditor\fR
.RS
Initialize the swift container daemons above
.RE

\fIaccount\fR, \fIaccount-auditor\fR, 
\fIaccount-reaper\fR, \fIaccount-replicator\fR, 
.RS
Initializes the swift account daemons above
.RE

\fIall\fR
.RS
Initializes \fBall\fR the swift daemons
.RE

\fImain\fR
.RS
Initializes all the \fBmain\fR swift daemons (proxy,container,account and object servers)
.RE

\fIrest\fR
.RS
Initializes all the other \fBswift background daemons\fR such as (updater, replicator,auditor,reaper)
.RE

.RE


.PP 
\fBCommands:\fR
.RS 2
\fIforce-reload\fR:   alias for reload

\fIno-daemon\fR:   start a server interactively

\fIno-wait\fR:   spawn server and return immediately

\fIonce\fR:   start server and run one pass on supporting daemons

\fIreload\fR:   graceful shutdown then restart on supporting servers

\fIrestart\fR:   stops then restarts server

\fIshutdown\fR:   allow current requests to finish on supporting servers
\fIstart\fR:   starts a server

\fIstatus\fR:   display status of tracked pids for server

\fIstop\fR:   stops a server
.RE


.PP 
\fBOptions:\fR
.RS 2
-h, --help            show this help message and exit
.RE	
.RS 2
-v, --verbose         display verbose output
.RE
.RS 2
-w, --no-wait         won't wait for server to start before returning
.RE  
.RS 2
-o, --once            only run one pass of daemon
.RE
.RS 2
-n, --no-daemon       start server interactively
.RE  
.RS 2
-g, --graceful        send SIGHUP to supporting servers
.RE 
.RS 2
-c N, --config-num=N  send command to the Nth server only
.RE



.SH DOCUMENTATION
.LP
More documentation about Openstack-Swift can be found at 
.BI http://swift.openstack.org/index.html

.SH AUTHOR
Originally written by Joao Marcelo Martins <btorch@gmail.com>

